const header = document.querySelector('header')
const h1 = document.createElement('h1')
const Novo = document.createTextNode("olá")
header.appendChild(h1)
header.appendChild(Novo)
const main = document.querySelector('main')
const div = document.createElement('div')
const di = document.createElement('div')
const h2 = document.createElement('h2')
const se = document.createTextNode("oi")
const p = document.createElement('p')
const sa = document.createTextNode("tchau")
const e = document.createElement('p')
const r = document.createTextNode('claro')
main.appendChild(div)
main.appendChild(di)
div.appendChild(h2)
div.appendChild(se)
div.appendChild(p)
div.appendChild(sa)
di.appendChild(h2)
di.appendChild(se)
di.appendChild(e)
di.appendChild(r)
main.style = "color: red";
header.style = "font-size: 200px"

